### ISSUE TITLE
cloud-prepare should support selecting a suitable GW instance type

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/cloud-prepare#107]
**What would you like to be added**:
While installing dedicated Gateway nodes in some clouds, the region may not support the requested instance type.
For example, AWS us-west-1 does not support m5n.large instance type. It would be useful if cloud-prepare library can support a mode where it can choose the most appropriate instance available in the region.

Currently, the signature for the API is 
```NewOcpGatewayDeployer(cloud api.Cloud, msDeployer ocp.MachineSetDeployer, instanceType string)```

We can modify the code to allow an empty instanceType and treat this as an option for cloud-prepare to choose the appropriate instance available in the region.

**Comment by nyechiel** [comment]
This was actually done for 0.11.
