### ISSUE TITLE
AWS: cloud-prepare fails if a security group already exists

### ISSUE THREAD

**Issue by skitt** [submariner-io/cloud-prepare#113]
**What happened**:

I deployed Submariner on a cluster, then removed it, and tried to prepare the cluster again for Submariner (the gateway node had been removed).

`cloud-prepare` failed with

```
 ✗ InvalidGroup.Duplicate: The security group 'skitt-1-c6nr4-submariner-gw-sg' already exists for VPC 'vpc-00b8d5512b0e9a056'
        status code: 400, request id: 770c894e-4bea-4ae1-abc6-c2fed115bb7e
Failed to prepare AWS cloud: InvalidGroup.Duplicate: The security group 'skitt-1-c6nr4-submariner-gw-sg' already exists for VPC 'vpc-00b8d5512b0e9a056'
        status code: 400, request id: 770c894e-4bea-4ae1-abc6-c2fed115bb7e
```

**What you expected to happen**:

The cluster to be set up for Submariner.

**How to reproduce it (as minimally and precisely as possible)**:

Run `cloud-prepare`, delete the gateway node, run `cloud-prepare` again.

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration: AWS
- Install tools: `subctl` (`devel`), `openshift-installer` 4.6.6
- Others:

**Comment by sridhargaddam** [comment]
cloud-prepare is normally expected to be idempotent and I remember running the command multiple times on AWS cluster without any issues. Looks like when the gateway node is deleted, the code-path is hitting some issue.

**Comment by sridhargaddam** [comment]
This needs to be investigated and if the problem is present, we will have to fix it.

**Comment by dfarrell07** [comment]
Discussing this on the PR/Issue scrub, we think we need to figure out exactly what was done to delete Submariner in order to reproduce this. This seems like it might be important/valid, but needs more digging.

**Comment by skitt** [comment]
I’ll try to reproduce this next week, and if it isn’t reproducible, close it.

**Comment by mkolesnik** [comment]
BTW we have [`cloud cleanup`](https://submariner.io/operations/deployment/subctl/#cloud-cleanup) commands which should be used to clean up after submariner is uninstalled from the cloud.
If you did `cloud prepare` -> `cloud cleanup` and then `cloud prepare` and it failed, seems valid, but if you didn't use `cloud cleanup` I don't think this bug is valid.

**Comment by mkolesnik** [comment]
@skitt did you manage to reproduce it?

**Comment by skitt** [comment]
Thanks for the ping, I haven’t been able to reproduce this.
