### ISSUE TITLE
Implement unit-tests for the prepare/cleanup on AWS

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/cloud-prepare#17]

**Comment by mkolesnik** [comment]
bump

**Comment by nyechiel** [comment]
@tpantelis are you working on this or planning to? I suggest to only leave one person as the assignee.

**Comment by tpantelis** [comment]
> @tpantelis are you working on this or planning to? I suggest to only leave one person as the assignee.

I'm planning to.
