### ISSUE TITLE
cloud-prepare: add support for OpenStack

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/cloud-prepare#19]
**What would you like to be added**:

Support for automated infra configuration of OpenStack-based clouds.

**Comment by nyechiel** [comment]
bump

**Comment by nyechiel** [comment]
@aswinsuryan can you update this one please?

**Comment by aswinsuryan** [comment]
This is done.

https://github.com/submariner-io/submariner-operator/issues/1725
https://github.com/submariner-io/cloud-prepare/issues/167
https://github.com/submariner-io/cloud-prepare/issues/166
