### ISSUE TITLE
cloud-prepare: add support for VMware

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/cloud-prepare#20]
**What would you like to be added**:

Support for automated infra configuration of VMware vSphere-based environments.

**Comment by nyechiel** [comment]
@skeeey @qiujian16 please assign it to yourself

**Comment by nyechiel** [comment]
bump

**Comment by dfarrell07** [comment]
@skeeey Still working on this or should I unassign you?

**Comment by skeeey** [comment]
@dfarrell07 I‘m not working on this now,  you can unassign me freely, thank you

**Comment by nyechiel** [comment]
For non-NSX VMware setups, no special prep is needed.
