### ISSUE TITLE
WIth dedicated node security group is associated with incorrect VM in cloud-prepare for Openstack

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/cloud-prepare#227]
**What happened**:
Security group is associated with incorrect VM in cloud-prepare for Openstack while using dedicated g/w node. Instead of the VM created for dedicated g/w node. It is getting associated with a different node. 

**What you expected to happen**:
Security groups should be associated with new node created which has the g/w node tag.

**How to reproduce it (as minimally and precisely as possible)**:
run cloud prepare rhos with dedicated g/w node set to true.

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
This seems like a blocker for 0.12?

**Comment by aswinsuryan** [comment]
> This seems like a blocker for 0.12?

As RHOS involves manual steps for installation with acm since there is no UI support, we can document this as well

**Comment by nyechiel** [comment]
@aswinsuryan does it worth a backport to `release-0.12`?

**Comment by aswinsuryan** [comment]
@nyechiel the backport is handled https://github.com/submariner-io/cloud-prepare/pull/245
