### ISSUE TITLE
OSP: Subctl cloud prepare not happening sometimes

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/cloud-prepare#261]
When running "subctl cloud prepare osp ..." on a fresh cluster, it properly configures the gateway node, creates the necessary Security Group rules and associates the SG to the nodes. However, if one of the existing nodes is already labelled as a gateway node and we run "subctl cloud prepare osp ..." it assumes that necessary steps are already done and is not associating the required Security Group rules on the nodes. 

Workaround:

- With `subctl` driven deployment:  delete the `submariner.io/gateway=true` label and re-run the `subctl cloud-prepare` command. 
- With ACM: uninstall the `submariner-addon` from the ManagedCluster and re-install it.

**Comment by nyechiel** [comment]
@aswinsuryan please ensure this gets merged and backported
