### ISSUE TITLE
Azure SDK migration

### ISSUE THREAD

**Issue by skitt** [submariner-io/cloud-prepare#311]
This week’s bump to the latest Azure SDK failed:

```
pkg/azure/azure.go:25:2: SA1019: package github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-03-01/network is deprecated: Please note, this package has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork). We strongly encourage you to upgrade to continue receiving updates. See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details. (staticcheck)
	"github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-03-01/network"
	^
```

See https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md for details.

**Comment by nyechiel** [comment]
@skitt @aswinsuryan how important this one is? should we address in 0.14?

**Comment by skitt** [comment]
It’s one of those tasks that’s not important now, but it might become a blocker if it stops us from upgrading to a version of the SDK that we need to fix something else (_e.g._ a security issue).

**Comment by nyechiel** [comment]
> It’s one of those tasks that’s not important now, but it might become a blocker if it stops us from upgrading to a version of the SDK that we need to fix something else (_e.g._ a security issue).

@tpantelis perhaps you can take a look at this for 0.14?

**Comment by tpantelis** [comment]
> @tpantelis perhaps you can take a look at this for 0.14?

Sure
