### ISSUE TITLE
Deprecate non-dedicated gateways on 0.15

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/cloud-prepare#603]
**What would you like to be removed**:
Let's deprecate this mode for 0.15 and remove it on 0.16

**Why is this needed**:
We're not actually testing or using non-dedicated gateway mode from cloud prepare.
Furthermore, a more K8s native approach is to deploy with LB mode which actually handles the cloud related operations properly.

From a technical debt perspective, the code is just sitting there and making cloud-prepare and subctl harder to maintain, with it removed we'll have an easier maintenance burden and could even further simplify the cloud prepare code.

**Comment by mkolesnik** [comment]
cc @skitt @tpantelis @aswinsuryan @sridhargaddam @vthapar

**Comment by nyechiel** [comment]
@sridhargaddam @aswinsuryan I think there was at least one platform (GCP?) where it was required?

**Comment by aswinsuryan** [comment]
@nyechiel the default is dedicated to all platforms now. We have an issue the other way around where in AWS we support only dedicated mode.

For load balancer mode support in ACM we may still need tagging(but not opening ports) for deploying submariner-gateway nodes, as we don't use subtle there. 

@yboaron Do you have any thoughts on load balancer support in ACM? I am not sure about the current status.

**Comment by mkolesnik** [comment]
> @nyechiel the default is dedicated to all platforms now. We have an issue the other way around where in AWS we support only dedicated mode.

Is it an issue though?

> For load balancer mode support in ACM we may still need tagging(but not opening ports) for deploying submariner-gateway nodes, as we don't use subtle there.

Tagging via ACM can be easily and better achieved without cloud prepare, so I wouldn't keep it for that purpose anyhow.

**Comment by nyechiel** [comment]
If there are no concerns from @yboaron, @aswinsuryan, or @sridhargaddam - +1 from me for deprecating the non-dedicated mode.

**Comment by yboaron** [comment]
@aswinsuryan Currently we support (tech preview) deployment using LB from ACM only for managed Openshift (ROSA and ARO) and we'll continue to deploy on supported platforms (AWS,GCP, etc) without LB. 

After we'll hear feedback about the experience of Submariner deployment using LB we could decide if we want to switch to LB for all the platforms.

As per LB support on the different platforms, we tested SM deployment (via subctl) with LB including some basic tests on AWS, GCP and AZURE and it looks OK , but we didn't check other aspects (eg: performance), also worth mentioning that LB is not supported on all OSP platforms.

I'm fine with deprecating this code, just wanted to clarify that in case we decide not to support LB for some reason, the only way to deploy SM is by using dedicated node.

**Comment by aswinsuryan** [comment]
@yboaron thanks for confirming. 


+1 ,  we can deprecate this code.
