### ISSUE TITLE
cloud-prepare: Extract GatewayDeployer interface

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/cloud-prepare#63]
Following discussion with OCM consumers it seems that it would be better to extract gateway deployment to a different API.

The proposed API is:
```go
type GatewayDeployInput struct {
	// List of ports to open externally so that Submariner can reach and be reached by other Submariners
	PublicPorts []PortSpec

	// Amount of gateways that are being deployed
	//  0 (AutoGateways) = Deploy gateways per the default deployer policy (Default if not specified)
	//
	// 1-* = Deploy the amount of gateways requested (May fail if there aren't enough public subnets)
	Gateways int
}

type GatewayDeployer interface {
	Deploy(input GatewayDeployInput, reporter Reporter) error
	Cleanup(reporter Reporter) error
}
```

**What would you like to be added**:

**Why is this needed**:

**Comment by mangelajo** [comment]
```

	// Amount of gateways that are being deployed
	//  0 (AutoGateways) = Deploy gateways per the default deployer policy (Default if not specified)
	//
	// 1-* = Deploy the amount of gateways requested (May fail if there aren't enough public subnets)
	Gateways int
```

What about no-gateways ?

Should we use 0 for "0 gateways"

And another constant we define (AutoGateways = "MAXINT"  ) for automatic?

**Comment by mkolesnik** [comment]
> What about no-gateways ?

Well it's a separate function now, so if you don't need dedicated gateways you simply dont call it..

> 
> Should we use 0 for "0 gateways"
> 
> And another constant we define (AutoGateways = "MAXINT" ) for automatic?

For backwards compatibility I kept 0 as max gateways. (As I said, for no gateways just don't call this function)
