### ISSUE TITLE
Cloud-prepare: Add support for configuring existing worker nodes as GW nodes on GCP

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/cloud-prepare#97]
**What would you like to be added**:
We need support for configuring one (or more) of worker nodes in the Cluster as Submariner Gateway nodes.
The following configuration has to be done for the Gateway nodes.

1. The GCP instance networkTag has to be updated to match the External Firewall Rules
2. The GCP instance should be associated with a public-ip
3. The K8s worker node should be tagged with submariner.io/gateway=true tag

Note: The following issue handles the dedicated Gateway node use-case https://github.com/submariner-io/cloud-prepare/issues/91

**Comment by maayanf24** [comment]
@sridhargaddam - can the issue be closed and mark as Done?

**Comment by sridhargaddam** [comment]
@maayanf24 yes, we can mark it as Done.
